from aiogram.dispatcher.filters.state import State, StatesGroup

class User(StatesGroup):
    user_id=State()
    user_contact=State()

class Reklama_photo(StatesGroup):
    reklama_fayl_nomi = State()
    reklama_text_matni = State()
    reklama_berish = State()
    d1 = State()
    d2 = State()
    d3 = State()
    d4 = State()
    d5 = State()
    d6 = State()
    d7 = State()
    d8 = State()
class Reklama_video(StatesGroup):
    reklama_fayl_nomi = State()
    reklama_text_matni = State()
    reklama_berish = State()
    d1 = State()
    d2 = State()
    d3 = State()
    d4 = State()
    d5 = State()
    d6 = State()
    d7 = State()
    d8 = State()

class Reklama_gif(StatesGroup):
    reklama_fayl_nomi = State()
    reklama_text_matni = State()
    reklama_berish = State()
    d1 = State()
    d2 = State()
    d3 = State()
    d4 = State()
    d5 = State()
    d6 = State()
    d7 = State()
    d8 = State()

class Reklama_fayl(StatesGroup):
    reklama_fayl_nomi = State()
    reklama_text_matni = State()
    reklama_berish = State()
    d1 = State()
    d2 = State()
    d3 = State()
    d4 = State()
    d5 = State()
    d6 = State()
    d7 = State()
    d8 = State()

class Reklama_audio(StatesGroup):
    reklama_fayl_nomi = State()
    reklama_text_matni = State()
    reklama_berish = State()
    d1 = State()
    d2 = State()
    d3 = State()
    d4 = State()
    d5 = State()
    d6 = State()
    d7 = State()
    d8 = State()
